name: fallchat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 1.19.2
  google_sign_in: 5.4.0
  flutterfire_cli: 0.2.4
  firebase_auth: 3.4.2
  lottie: 1.3.0
  introduction_screen: 3.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true

